artifact_location: file:///home/naradaw/code/GCNTFT/tft_src/../mlflow_experiments/946752409671630194
creation_time: 1743778276863
experiment_id: '946752409671630194'
last_update_time: 1743778276863
lifecycle_stage: active
name: tft_only_forecasting_1_loc_Shadipur
